# Generated by Django 6.0.3 on 2026-03-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslider',
            name='image_url',
            field=models.URLField(blank=True, help_text='External URL for background image', null=True),
        ),
        migrations.AddField(
            model_name='heroslider',
            name='video_url',
            field=models.URLField(blank=True, help_text='External URL for background video', null=True),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sliders/'),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='sliders/videos/'),
        ),
    ]
