# Generated by Django 6.0.3 on 2026-03-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0002_heroslider_image_url_heroslider_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslider',
            name='image',
            field=models.ImageField(blank=True, help_text='Desktop slider image. Recommended: 1920x800px. JPG, WEBP. Max 2MB.', null=True, upload_to='sliders/'),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='image_url',
            field=models.URLField(blank=True, help_text='External URL for background image.', null=True),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='video',
            field=models.FileField(blank=True, help_text='Background video. Recommended: MP4 format. Max 5MB for performance.', null=True, upload_to='sliders/videos/'),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='video_url',
            field=models.URLField(blank=True, help_text='External URL for background video (YouTube/Vimeo not supported for direct background).', null=True),
        ),
    ]
