# Generated by Django 6.0.3 on 2026-04-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0003_alter_heroslider_image_alter_heroslider_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslider',
            name='button_link',
            field=models.CharField(default='/products/', max_length=255),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='button_text',
            field=models.CharField(default='Shop Now', max_length=100),
        ),
    ]
