# Generated by Django 6.0.3 on 2026-04-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0004_alter_heroslider_button_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslider',
            name='button_2_link',
            field=models.CharField(default='/contact/', max_length=255),
        ),
        migrations.AddField(
            model_name='heroslider',
            name='button_2_text',
            field=models.CharField(default='Enquiry', max_length=100),
        ),
    ]
