# Generated by Django 6.0.3 on 2026-04-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0005_heroslider_button_2_link_heroslider_button_2_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroslider',
            name='button_2_link',
        ),
        migrations.RemoveField(
            model_name='heroslider',
            name='button_2_text',
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='button_link',
            field=models.CharField(default='/contact-us/', max_length=255),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='button_text',
            field=models.CharField(default='Enquire Now', max_length=100),
        ),
    ]
