# Generated by Django 6.0.3 on 2026-04-08 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0006_remove_heroslider_button_2_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name for management.', max_length=100)),
                ('layout', models.CharField(choices=[('1_col', '1-Column (Full Width)'), ('2_col', '2-Column (Side by Side)'), ('3_col', '3-Column (Row)'), ('mosaic', 'Mosaic/Grid')], default='1_col', max_length=20)),
                ('shape', models.CharField(choices=[('rectangular', 'Rectangular'), ('rounded', 'Rounded Corners'), ('pill', 'Pill Shape')], default='rounded', max_length=20)),
                ('homepage_order', models.PositiveIntegerField(default=0, help_text='Order in which this banner appears on homepage.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Promo Banner Section',
                'verbose_name_plural': 'Promo Banner Sections',
                'ordering': ['homepage_order'],
            },
        ),
        migrations.CreateModel(
            name='BannerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('image_url', models.URLField(blank=True, help_text='Direct link if image is externally hosted.', null=True)),
                ('link', models.CharField(blank=True, help_text='Link path (e.g., /shop/ or full URL).', max_length=255)),
                ('title', models.CharField(blank=True, help_text='Optional overlay text.', max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('banner_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sliders.promobanner')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
