# Generated by Django 6.0.3 on 2026-04-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0007_promobanner_banneritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslider',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Removed')], default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Removed')], default=True, verbose_name='Status'),
        ),
    ]
