# Generated by Django 6.0.3 on 2026-04-10 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0008_alter_heroslider_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroslider',
            options={'ordering': ['order'], 'verbose_name': 'Banner', 'verbose_name_plural': 'Banners'},
        ),
    ]
