# Generated by Django 6.0.3 on 2026-04-15 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0009_alter_heroslider_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promobanner',
            options={'ordering': ['homepage_order'], 'verbose_name': 'Promo Section', 'verbose_name_plural': 'Promo Sections'},
        ),
    ]
