# Generated by Django 6.0.3 on 2026-04-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0010_alter_promobanner_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='banneritem',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
