# Generated by Django 6.0.3 on 2026-04-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0011_banneritem_image_alt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroslider',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='heroslider',
            name='badge_text',
            field=models.CharField(blank=True, default='Elite Collection', max_length=100),
        ),
        migrations.AddField(
            model_name='heroslider',
            name='description',
            field=models.TextField(blank=True, default='Precision medical equipment delivered with royalty-class service.'),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='title',
            field=models.CharField(default='Royal Quality Healthcare', max_length=255),
        ),
    ]
