# Generated by Django 6.0.3 on 2026-04-16 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0012_remove_heroslider_subtitle_heroslider_badge_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroslider',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='heroslider',
            name='button_text',
        ),
    ]
