# Generated by Django 6.0.3 on 2026-04-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0013_remove_heroslider_button_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslider',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Alt text for the slider background image.', max_length=255),
        ),
    ]
