# Generated by Django 6.0.3 on 2026-04-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0014_heroslider_image_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslider',
            name='badge_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
