# Generated by Django 6.0.3 on 2026-03-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_client_newslettersubscriber_socialpost_testimonial_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
        migrations.AddField(
            model_name='client',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clients/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='abudhabi_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='dubai_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='social/'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
