# Generated by Django 6.0.3 on 2026-03-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_newslettersubscriber_client_logo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, help_text='Client Logo. Recommended: 300x120px (Transparent PNG). Max 500KB.', null=True, upload_to='clients/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Browser Icon. Recommended: 32x32px or 64x64px. ICO or PNG.', null=True, upload_to='settings/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Primary Brand Logo. Recommended: 500x120px (Transparent PNG). Max 1MB.', null=True, upload_to='settings/'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='image',
            field=models.ImageField(blank=True, help_text='Instagram Preview. Recommended: 1080x1080px (Square). JPG, WEBP. Max 2MB.', null=True, upload_to='social/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, help_text='Client Photo. Recommended: 200x200px (1:1). JPG, PNG. Max 500KB.', null=True, upload_to='testimonials/'),
        ),
    ]
