# Generated by Django 6.0.3 on 2026-03-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_enable_email_notifications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Storefront Photo. Recommended: 800x600px. JPG, WEBP. Max 1MB.', null=True, upload_to='stores/')),
                ('image_url', models.URLField(blank=True, help_text='Alternative: Direct link to an externally hosted image.', null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(help_text='e.g. Dubai, Sharjah, Abu Dhabi', max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('map_url', models.URLField(help_text='Link to the location on Google Maps (Get Directions)', verbose_name='Google Maps URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Enabled')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
