# Generated by Django 6.0.3 on 2026-04-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_storelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_copyright_text',
            field=models.CharField(blank=True, default='All rights reserved.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_legal_title',
            field=models.CharField(default='Legal', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_newsletter_title',
            field=models.CharField(default='Subscribe to our Newsletter', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_quick_links_title',
            field=models.CharField(default='Quick Links', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_support_title',
            field=models.CharField(default='Support', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_subtitle',
            field=models.CharField(default='JOY OF MOBILITY', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_title',
            field=models.CharField(default='JKR International', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hp_categories_title',
            field=models.CharField(default='Product <span class="text-primary">Categories</span>', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hp_clients_title',
            field=models.CharField(default='Our Clients', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hp_collections_subtitle',
            field=models.TextField(blank=True, default='Handpicked selection of premium medical equipment and essential supplies.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hp_collections_title',
            field=models.CharField(default='Exclusive <span class="text-primary">Collections</span>', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hp_gallery_title',
            field=models.CharField(default='Latest <span class="text-primary">Gallery & Updates</span>', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hp_latest_products_empty',
            field=models.CharField(blank=True, default='Stay tuned for our latest medical products.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hp_latest_products_subtitle',
            field=models.TextField(blank=True, default='Discover our newest medical innovations and technology.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hp_latest_products_title',
            field=models.CharField(default='Explore <span class="text-primary">Latest Products</span>', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hp_partners_subtitle',
            field=models.TextField(blank=True, default="100+ partnerships we've made ensure the quality of products we distribute"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hp_partners_title',
            field=models.CharField(default='We Deal with,', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hp_services_overtitle',
            field=models.CharField(default='OUR SERVICES', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hp_services_subtitle',
            field=models.TextField(blank=True, default='We are dedicated to maintaining the health and effectiveness of your essential diagnostic equipment.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hp_services_title',
            field=models.CharField(default='Specialized Maintenance Services', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hp_social_overtitle',
            field=models.CharField(default='GO SOCIAL WITH US', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hp_social_subtitle',
            field=models.CharField(default='Follow our Instagram @jkrinternational', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hp_testimonials_overtitle',
            field=models.CharField(default='TESTIMONIALS', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hp_testimonials_title',
            field=models.CharField(default='Read what our clients have to share!', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pd_related_title',
            field=models.CharField(default='Related Products', max_length=255),
        ),
    ]
