# Generated by Django 6.0.3 on 2026-04-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sitesettings_footer_copyright_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='pd_related_count',
            field=models.PositiveIntegerField(default=4, verbose_name='Number of Related Products'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pd_show_related',
            field=models.BooleanField(default=True, verbose_name='Show Related Products'),
        ),
    ]
