# Generated by Django 6.0.3 on 2026-04-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sitesettings_pd_related_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='fav_text',
            field=models.CharField(default='JKR', help_text='Small text shown near favicon or in tab.', max_length=50),
        ),
    ]
