# Generated by Django 6.0.3 on 2026-04-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sitesettings_fav_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#114084', help_text='Main brand color (Buttons, Headlines)', max_length=20)),
                ('secondary_color', models.CharField(default='#3498db', help_text='Secondary actions and accents', max_length=20)),
                ('accent_color', models.CharField(default='#2271b1', help_text='Hover states and links', max_length=20)),
                ('bg_light', models.CharField(default='#f8f9fa', help_text='Light mode background', max_length=20)),
                ('bg_dark', models.CharField(default='#121212', help_text='Dark mode background', max_length=20)),
                ('text_main', models.CharField(default='#1a1a1a', help_text='Primary text color', max_length=20)),
                ('text_muted', models.CharField(default='#6c757d', help_text='Secondary/muted text', max_length=20)),
                ('body_font_family', models.CharField(default="'Outfit', sans-serif", help_text='Main body text font', max_length=255)),
                ('heading_font_family', models.CharField(default="'Outfit', sans-serif", help_text='Headline font', max_length=255)),
                ('base_font_size', models.PositiveIntegerField(default=16, help_text='Base font size in px')),
                ('border_radius', models.CharField(default='16px', help_text='Radius for cards, buttons, images', max_length=20)),
                ('button_style', models.CharField(choices=[('square', 'Square'), ('rounded', 'Rounded'), ('pill', 'Pill')], default='pill', max_length=20)),
                ('card_shadow', models.CharField(default='0 8px 30px rgba(0,0,0,0.08)', help_text='CSS shadow for cards', max_length=100)),
                ('glassmorphism', models.BooleanField(default=True, help_text='Enable glass effects for headers and cards')),
                ('enable_aos', models.BooleanField(default=True, verbose_name='Enable Scroll Animations')),
                ('animation_duration', models.PositiveIntegerField(default=800, help_text='Default AOS duration in ms')),
                ('page_transitions', models.BooleanField(default=True, help_text='Enable smooth page fade-in')),
                ('dark_mode_default', models.BooleanField(default=False, verbose_name='Default to Dark Mode')),
            ],
            options={
                'verbose_name': 'Frontend Design Control',
                'verbose_name_plural': 'Frontend Design Control',
            },
        ),
    ]
