# Generated by Django 6.0.3 on 2026-04-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_frontenddesign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='fav_text',
            field=models.CharField(default='Demo', help_text='Small text shown near favicon or in tab.', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='header_subtitle',
            field=models.CharField(default='PREMIUM QUALITY', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='header_title',
            field=models.CharField(default='Demo Store', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_handle',
            field=models.CharField(blank=True, default='@demostore', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Demo Store', max_length=255),
        ),
    ]
