# Generated by Django 6.0.3 on 2026-04-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_frontenddesign_alter_sitesettings_fav_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='button_style',
            field=models.CharField(choices=[('rounded', 'Rounded (Pill)'), ('soft', 'Soft (Slightly Rounded)'), ('sharp', 'Sharp (Square)')], default='rounded', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='dark_mode_enabled',
            field=models.BooleanField(default=False, verbose_name='Enable Dark Mode'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_glassmorphism',
            field=models.BooleanField(default=False, verbose_name='Enable Glassmorphism'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_neumorphism',
            field=models.BooleanField(default=False, verbose_name='Enable Neumorphism'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='font_body',
            field=models.CharField(default="'Montserrat', sans-serif", help_text='CSS font-family value', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='font_heading',
            field=models.CharField(default="'Montserrat', sans-serif", help_text='CSS font-family value', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='layout_style',
            field=models.CharField(choices=[('boxed', 'Boxed Layout'), ('full', 'Full Width Layout')], default='full', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#114084', help_text='Hex code, e.g. #114084', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='secondary_color',
            field=models.CharField(default='#005CB9', help_text='Hex code, e.g. #005CB9', max_length=20),
        ),
    ]
