# Generated by Django 6.0.3 on 2026-04-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sitesettings_button_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='accent_glow_color',
            field=models.CharField(default='#0081ff', help_text='Color for ambient glow effects.', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='card_style',
            field=models.CharField(choices=[('standard', 'Standard Rounded'), ('glass', 'Glass Edge'), ('minimal', 'Minimalist (No Border)')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_ambient_glow',
            field=models.BooleanField(default=True, verbose_name='Enable Ambient Glow Background'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_animations',
            field=models.BooleanField(default=True, verbose_name='Enable Scroll Animations (AOS)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='global_animation_type',
            field=models.CharField(choices=[('fade-up', 'Fade Up'), ('fade-down', 'Fade Down'), ('zoom-in', 'Zoom In'), ('flip-left', 'Flip Left'), ('none', 'No Animation')], default='fade-up', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_style',
            field=models.CharField(choices=[('pill', 'Pill (Fully Rounded)'), ('soft', 'Soft (8px Radius)'), ('sharp', 'Sharp (Square)')], default='pill', max_length=20),
        ),
    ]
