# Generated by Django 6.0.3 on 2026-04-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_sitesettings_accent_glow_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#114084', help_text='Hex code, e.g. #114084', max_length=20)),
                ('secondary_color', models.CharField(default='#005CB9', help_text='Hex code, e.g. #005CB9', max_length=20)),
                ('accent_glow_color', models.CharField(default='#0081ff', help_text='Color for ambient glow effects.', max_length=20)),
                ('font_body', models.CharField(default="'Montserrat', sans-serif", help_text='CSS font-family value', max_length=100)),
                ('font_heading', models.CharField(default="'Montserrat', sans-serif", help_text='CSS font-family value', max_length=100)),
                ('enable_glassmorphism', models.BooleanField(default=False, verbose_name='Enable Glassmorphism')),
                ('enable_neumorphism', models.BooleanField(default=False, verbose_name='Enable Neumorphism')),
                ('enable_ambient_glow', models.BooleanField(default=True, verbose_name='Enable Ambient Glow Background')),
                ('enable_animations', models.BooleanField(default=True, verbose_name='Enable Scroll Animations (AOS)')),
                ('button_style', models.CharField(choices=[('pill', 'Pill (Fully Rounded)'), ('soft', 'Soft (8px Radius)'), ('sharp', 'Sharp (Square)')], default='pill', max_length=20)),
                ('card_style', models.CharField(choices=[('standard', 'Standard Rounded'), ('glass', 'Glass Edge'), ('minimal', 'Minimalist (No Border)')], default='standard', max_length=20)),
                ('layout_style', models.CharField(choices=[('boxed', 'Boxed Layout'), ('full', 'Full Width Layout')], default='full', max_length=20)),
                ('dark_mode_enabled', models.BooleanField(default=False, verbose_name='Enable Dark Mode')),
                ('global_animation_type', models.CharField(choices=[('fade-up', 'Fade Up'), ('fade-down', 'Fade Down'), ('zoom-in', 'Zoom In'), ('flip-left', 'Flip Left'), ('none', 'No Animation')], default='fade-up', max_length=20)),
            ],
            options={
                'verbose_name': 'Design Configuration',
                'verbose_name_plural': 'Design Configuration',
            },
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='accent_glow_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='button_style',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='card_style',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='dark_mode_enabled',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='enable_ambient_glow',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='enable_animations',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='enable_glassmorphism',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='enable_neumorphism',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='font_body',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='font_heading',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='global_animation_type',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='layout_style',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='secondary_color',
        ),
    ]
