# Generated by Django 6.0.3 on 2026-04-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_designsettings_remove_sitesettings_accent_glow_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='header_subtitle',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='header_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hp_categories_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hp_clients_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hp_collections_subtitle',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hp_collections_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hp_gallery_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hp_latest_products_empty',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hp_latest_products_subtitle',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hp_latest_products_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hp_partners_subtitle',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hp_partners_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hp_services_overtitle',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hp_services_subtitle',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hp_services_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hp_social_overtitle',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hp_social_subtitle',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hp_testimonials_overtitle',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hp_testimonials_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='pd_related_count',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='pd_related_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='pd_show_related',
        ),
        migrations.AddField(
            model_name='designsettings',
            name='header_subtitle',
            field=models.CharField(default='Empowering Your Vision', max_length=255),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='header_title',
            field=models.CharField(default='Demo International', max_length=255),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='hp_categories_title',
            field=models.CharField(default='Product <span class="text-primary">Categories</span>', max_length=255),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='hp_clients_title',
            field=models.CharField(default='Our Clients', max_length=255),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='hp_collections_subtitle',
            field=models.TextField(blank=True, default='Handpicked selection of premium medical equipment and essential supplies.'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='hp_collections_title',
            field=models.CharField(default='Exclusive <span class="text-primary">Collections</span>', max_length=255),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='hp_gallery_title',
            field=models.CharField(default='Latest <span class="text-primary">Gallery & Updates</span>', max_length=255),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='hp_latest_products_empty',
            field=models.CharField(blank=True, default='Stay tuned for our latest medical products.', max_length=255),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='hp_latest_products_subtitle',
            field=models.TextField(blank=True, default='Discover our newest medical innovations and technology.'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='hp_latest_products_title',
            field=models.CharField(default='Explore <span class="text-primary">Latest Products</span>', max_length=255),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='hp_partners_subtitle',
            field=models.TextField(blank=True, default="100+ partnerships we've made ensure the quality of products we distribute"),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='hp_partners_title',
            field=models.CharField(default='We Deal with,', max_length=255),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='hp_services_overtitle',
            field=models.CharField(default='OUR SERVICES', max_length=255),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='hp_services_subtitle',
            field=models.TextField(blank=True, default='We are dedicated to maintaining the health and effectiveness of your essential diagnostic equipment.'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='hp_services_title',
            field=models.CharField(default='Specialized Maintenance Services', max_length=255),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='hp_social_overtitle',
            field=models.CharField(default='GO SOCIAL WITH US', max_length=255),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='hp_social_subtitle',
            field=models.CharField(default='Follow our Instagram @demo_intl', max_length=255),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='hp_testimonials_overtitle',
            field=models.CharField(default='TESTIMONIALS', max_length=255),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='hp_testimonials_title',
            field=models.CharField(default='Read what our clients have to share!', max_length=255),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='pd_related_count',
            field=models.PositiveIntegerField(default=4, verbose_name='Number of Related Products'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='pd_related_title',
            field=models.CharField(default='Related Products', max_length=255),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='pd_show_related',
            field=models.BooleanField(default=True, verbose_name='Show Related Products'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='fav_text',
            field=models.CharField(default='Demo', help_text='Small text shown near favicon or in tab.', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_handle',
            field=models.CharField(blank=True, default='@demo_intl', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Demo International', max_length=255),
        ),
    ]
