# Generated by Django 6.0.3 on 2026-04-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_sitesettings_header_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='Paste SVG code for logo here.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='branch1_name',
            field=models.CharField(default='Dubai', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='branch2_name',
            field=models.CharField(default='Abu Dhabi', max_length=100),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='Paste SVG code here.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='abudhabi_address',
            field=models.TextField(blank=True, verbose_name='Branch 2 Address'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='dubai_address',
            field=models.TextField(blank=True, verbose_name='Branch 1 Address'),
        ),
    ]
