# Generated by Django 6.0.3 on 2026-04-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_announcementbar_searchindex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementbar',
            name='closable',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='User Closable'),
        ),
        migrations.AlterField(
            model_name='announcementbar',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Removed')], default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Removed')], default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='dark_mode_enabled',
            field=models.BooleanField(choices=[(True, 'Enabled'), (False, 'Disabled')], default=False, verbose_name='Dark Mode'),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='enable_ambient_glow',
            field=models.BooleanField(choices=[(True, 'Enabled'), (False, 'Disabled')], default=True, verbose_name='Ambient Glow'),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='enable_animations',
            field=models.BooleanField(choices=[(True, 'Enabled'), (False, 'Disabled')], default=True, verbose_name='Scroll Animations'),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='enable_glassmorphism',
            field=models.BooleanField(choices=[(True, 'Enabled'), (False, 'Disabled')], default=False, verbose_name='Glassmorphism'),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='enable_neumorphism',
            field=models.BooleanField(choices=[(True, 'Enabled'), (False, 'Disabled')], default=False, verbose_name='Neumorphism'),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='pd_show_related',
            field=models.BooleanField(choices=[(True, 'Show'), (False, 'Hide')], default=True, verbose_name='Related Products'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='enable_email_notifications',
            field=models.BooleanField(choices=[(True, 'Enabled'), (False, 'Disabled')], default=True, verbose_name='Email Notifications'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='enable_sms_notifications',
            field=models.BooleanField(choices=[(True, 'Enabled'), (False, 'Disabled')], default=False, verbose_name='SMS Notifications'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='enable_whatsapp_notifications',
            field=models.BooleanField(choices=[(True, 'Enabled'), (False, 'Disabled')], default=False, verbose_name='WhatsApp Notifications'),
        ),
        migrations.AlterField(
            model_name='storelocation',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Removed')], default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Removed')], default=True, verbose_name='Status'),
        ),
    ]
