# Generated by Django 6.0.3 on 2026-04-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_announcementbar_closable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designsettings',
            name='footer_bg_color',
            field=models.CharField(default='#1a1a1a', help_text='Background color for the site footer. e.g. #1a1a1a', max_length=20),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='header_bg_color',
            field=models.CharField(default='#ffffff', help_text='Background color for the main header bar. e.g. #ffffff', max_length=20),
        ),
    ]
