# Generated by Django 6.0.3 on 2026-04-10 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_header_footer_colors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcementbar',
            options={'verbose_name': 'Top Bar Message', 'verbose_name_plural': 'Top Bar Messages'},
        ),
        migrations.AlterModelOptions(
            name='designsettings',
            options={'verbose_name': 'Theme Settings', 'verbose_name_plural': 'Theme Settings'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Website Settings', 'verbose_name_plural': 'Website Settings'},
        ),
    ]
