# Generated by Django 6.0.3 on 2026-04-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_announcementbar_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designsettings',
            name='counter_animation_speed',
            field=models.PositiveIntegerField(choices=[(3000, 'Conservative (3s)'), (2000, 'Standard (2s)'), (1000, 'Fast (1s)'), (500, 'Instant (0.5s)')], default=2000, verbose_name='Counter Animation Duration (ms)'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='counter_animation_style',
            field=models.CharField(choices=[('runner', 'Progressive Runner (Count-up)'), ('fade', 'Simple Fade-in (No Counting)'), ('zoom', 'Zoom-in Count (Speedy)')], default='runner', max_length=20, verbose_name='Counter Animation Style'),
        ),
    ]
