# Generated by Django 6.0.3 on 2026-04-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_designsettings_counter_animation_speed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designsettings',
            name='button_style',
        ),
        migrations.RemoveField(
            model_name='designsettings',
            name='card_style',
        ),
        migrations.RemoveField(
            model_name='designsettings',
            name='dark_mode_enabled',
        ),
        migrations.RemoveField(
            model_name='designsettings',
            name='font_body',
        ),
        migrations.RemoveField(
            model_name='designsettings',
            name='font_heading',
        ),
        migrations.RemoveField(
            model_name='designsettings',
            name='header_subtitle',
        ),
        migrations.RemoveField(
            model_name='designsettings',
            name='header_title',
        ),
        migrations.RemoveField(
            model_name='designsettings',
            name='hp_latest_products_empty',
        ),
        migrations.RemoveField(
            model_name='designsettings',
            name='hp_partners_subtitle',
        ),
        migrations.RemoveField(
            model_name='designsettings',
            name='hp_services_overtitle',
        ),
        migrations.RemoveField(
            model_name='designsettings',
            name='hp_services_subtitle',
        ),
        migrations.RemoveField(
            model_name='designsettings',
            name='hp_social_overtitle',
        ),
        migrations.RemoveField(
            model_name='designsettings',
            name='hp_social_subtitle',
        ),
        migrations.RemoveField(
            model_name='designsettings',
            name='hp_testimonials_overtitle',
        ),
        migrations.RemoveField(
            model_name='designsettings',
            name='layout_style',
        ),
        migrations.AddField(
            model_name='designsettings',
            name='border_color',
            field=models.CharField(default='#e2e8f0', help_text='Default border color.', max_length=50),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='button_radius',
            field=models.CharField(default='9999px', help_text='e.g. 9999px (Pill), 12px (Soft)', max_length=50),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='card_bg_color',
            field=models.CharField(default='#ffffff', help_text='Card/Container background.', max_length=50),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='card_radius',
            field=models.CharField(default='24px', help_text='e.g. 24px, 1.5rem', max_length=50),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='cart_page_title',
            field=models.CharField(default='Your <span class="italic text-primary">Cart</span>', max_length=255),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='checkout_page_title',
            field=models.CharField(default='Secure <span class="text-primary">Checkout</span>', max_length=255),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='contact_page_title',
            field=models.CharField(default='Contact <span class="text-primary">Us</span>', max_length=255),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='container_radius',
            field=models.CharField(default='40px', help_text='e.g. 40px, 2rem', max_length=50),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='font_main',
            field=models.CharField(choices=[("'Noto Serif', serif", 'Noto Serif (Classic/Premium)'), ("'Inter', sans-serif", 'Inter (Modern/Clean)'), ("'Plus Jakarta Sans', sans-serif", 'Jakarta (High-tech)'), ("'Montserrat', sans-serif", 'Montserrat (Bold/Social)')], default="'Noto Serif', serif", max_length=100),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='font_secondary',
            field=models.CharField(choices=[("'Noto Serif', serif", 'Noto Serif (Classic/Premium)'), ("'Inter', sans-serif", 'Inter (Modern/Clean)'), ("'Plus Jakarta Sans', sans-serif", 'Jakarta (High-tech)'), ("'Montserrat', sans-serif", 'Montserrat (Bold/Social)')], default="'Noto Serif', serif", max_length=100),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='footer_text_color',
            field=models.CharField(default='#94a3b8', max_length=50),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='header_text_color',
            field=models.CharField(default='#1e293b', max_length=50),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='hp_hero_subtitle',
            field=models.TextField(blank=True, default='Precision medical equipment delivered with royalty-class service.'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='hp_hero_title',
            field=models.CharField(default='Royal Quality <span class="italic">Healthcare</span>', max_length=255),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='hp_social_title',
            field=models.CharField(default='Join Our Network', max_length=255),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='image_radius',
            field=models.CharField(default='20px', max_length=50),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='orders_page_title',
            field=models.CharField(default='Order <span class="text-primary">History</span>', max_length=255),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='profile_page_title',
            field=models.CharField(default='My <span class="text-primary">Account</span>', max_length=255),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='search_page_title',
            field=models.CharField(default='Search <span class="text-primary">Results</span>', max_length=255),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='surface_bg_color',
            field=models.CharField(default='#f8fafc', help_text='Main site background.', max_length=50),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='text_primary_color',
            field=models.CharField(default='#1e293b', help_text='Main text color.', max_length=50),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='text_secondary_color',
            field=models.CharField(default='#64748b', help_text='Muted text/labels.', max_length=50),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='text_white_color',
            field=models.CharField(default='#ffffff', help_text='Text on dark backgrounds.', max_length=50),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='wishlist_page_title',
            field=models.CharField(default='My <span class="italic text-primary">Wishlist</span>', max_length=255),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='accent_glow_color',
            field=models.CharField(default='#0081ff', help_text='Ambient glow effects.', max_length=50),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='counter_animation_speed',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='counter_animation_style',
            field=models.CharField(default='runner', max_length=50),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='enable_glassmorphism',
            field=models.BooleanField(choices=[(True, 'Enabled'), (False, 'Disabled')], default=True, verbose_name='Glassmorphism'),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='footer_bg_color',
            field=models.CharField(default='#1a1a1a', max_length=50),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='header_bg_color',
            field=models.CharField(default='#ffffff', max_length=50),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='hp_clients_title',
            field=models.CharField(default='Trusted By', max_length=255),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='hp_collections_subtitle',
            field=models.TextField(blank=True, default='Handpicked selection of premium medical equipment.'),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='hp_gallery_title',
            field=models.CharField(default='Visual <span class="text-primary">Updates</span>', max_length=255),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='hp_latest_products_subtitle',
            field=models.TextField(blank=True, default='Discover our newest medical innovations.'),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='hp_partners_title',
            field=models.CharField(default='Our Global Partners', max_length=255),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='hp_services_title',
            field=models.CharField(default='Maintenance Support', max_length=255),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='hp_testimonials_title',
            field=models.CharField(default='Client Testimonials', max_length=255),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='pd_related_count',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='pd_related_title',
            field=models.CharField(default='You May Also Like', max_length=255),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='primary_color',
            field=models.CharField(default='#114084', help_text='Primary Brand Color (Buttons, Links, Accents).', max_length=50),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='secondary_color',
            field=models.CharField(default='#005CB9', help_text='Secondary/Hover states.', max_length=50),
        ),
    ]
