# Generated by Django 6.0.3 on 2026-04-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_designsettings_button_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designsettings',
            name='show_header_account',
            field=models.BooleanField(choices=[(True, 'Show'), (False, 'Hide')], default=True, verbose_name='Header Account'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='show_header_cart',
            field=models.BooleanField(choices=[(True, 'Show'), (False, 'Hide')], default=True, verbose_name='Header Cart'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='show_header_search',
            field=models.BooleanField(choices=[(True, 'Show'), (False, 'Hide')], default=True, verbose_name='Header Search'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='show_header_wishlist',
            field=models.BooleanField(choices=[(True, 'Show'), (False, 'Hide')], default=True, verbose_name='Header Wishlist'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='show_hp_brands',
            field=models.BooleanField(choices=[(True, 'Show'), (False, 'Hide')], default=True, verbose_name='Home Brands'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='show_hp_categories',
            field=models.BooleanField(choices=[(True, 'Show'), (False, 'Hide')], default=True, verbose_name='Home Categories'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='show_hp_clients',
            field=models.BooleanField(choices=[(True, 'Show'), (False, 'Hide')], default=True, verbose_name='Home Clients'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='show_hp_latest_products',
            field=models.BooleanField(choices=[(True, 'Show'), (False, 'Hide')], default=True, verbose_name='Home Latest Products'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='show_hp_social',
            field=models.BooleanField(choices=[(True, 'Show'), (False, 'Hide')], default=True, verbose_name='Home Social'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='show_hp_testimonials',
            field=models.BooleanField(choices=[(True, 'Show'), (False, 'Hide')], default=True, verbose_name='Home Testimonials'),
        ),
    ]
