# Generated by Django 6.0.3 on 2026-04-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_designsettings_show_header_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designsettings',
            name='show_hp_collections',
            field=models.BooleanField(choices=[(True, 'Show'), (False, 'Hide')], default=True, verbose_name='Home Collections'),
        ),
    ]
