# Generated by Django 6.0.3 on 2026-04-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_designsettings_show_hp_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='designsettings',
            name='hp_collections_layout',
            field=models.CharField(choices=[('1_col', '1-Image (Full Width)'), ('2_col', '2-Images (Side-by-Side)'), ('3_col', '3-Images (Gallery)')], default='3_col', max_length=20, verbose_name='Home Collections Layout'),
        ),
    ]
