# Generated by Django 6.0.3 on 2026-04-16 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_designsettings_hp_collections_layout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designsettings',
            name='hp_collections_layout',
        ),
    ]
