# Generated by Django 6.0.3 on 2026-04-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_designsettings_hp_collections_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='designsettings',
            name='theme_variant',
            field=models.CharField(choices=[('classic', 'Classic (Professional)'), ('modern', 'Modern (Clean & Bold)'), ('luxury', 'Luxury (Royal & Elegant)')], default='classic', max_length=20, verbose_name='Visual Theme Engine'),
        ),
    ]
