# Generated by Django 6.0.3 on 2026-04-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_designsettings_theme_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Global SEO Keywords.', max_length=512),
        ),
    ]
