# Generated by Django 6.0.3 on 2026-04-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_sitesettings_meta_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Alt text for the client logo.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_pixel_id',
            field=models.CharField(blank=True, help_text='Meta Pixel ID', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='GA4 Measurement ID (e.g. G-XXXXXXX)', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_site_verification_id',
            field=models.CharField(blank=True, help_text='Verification token for Google Search Console.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='robots_txt',
            field=models.TextField(blank=True, help_text='Custom robots.txt content. Leave blank to use default.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='schema_markup',
            field=models.TextField(blank=True, help_text='Custom JSON-LD schema markup for the homepage.'),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Alt text for the social post image.', max_length=255),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Alt text for the store photo.', max_length=255),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Alt text for the client photo.', max_length=255),
        ),
    ]
