# Generated by Django 6.0.3 on 2026-03-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_galleryitem_image_url_missionvision_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended: 1000x1000px or 1200x800px. JPG, WEBP. Max 2MB.', null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='missionvision',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200x800px. JPG, WEBP. Max 2MB.', null=True, upload_to='pages/'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, help_text='Brand Logo. Recommended: 400x400px (Transparent PNG). Max 500KB.', null=True, upload_to='partners/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, help_text='Service Icon. Recommended: 256x256px (Transparent PNG). Max 500KB.', null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Recommended: 800x450px. JPG, WEBP. Max 1MB.', null=True, upload_to='about/videos/'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Alternative external link for thumbnail.', null=True),
        ),
    ]
