# Generated by Django 6.0.3 on 2026-04-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_galleryitem_image_alter_missionvision_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('about', 'About Us'), ('products', 'Products'), ('services', 'Services'), ('gallery', 'Gallery'), ('stores', 'Stores'), ('blog', 'Blog'), ('contact', 'Contact Us')], max_length=20, unique=True)),
                ('hero_image', models.ImageField(blank=True, help_text='Recommended: 1920x600px. JPG, WEBP. Max 2MB.', null=True, upload_to='heroes/')),
                ('hero_image_url', models.URLField(blank=True, help_text='Alternative external link for hero image.', null=True)),
                ('title', models.CharField(blank=True, help_text='Main title on the hero section.', max_length=255)),
                ('subtitle', models.TextField(blank=True, help_text='Subtitle or description below the title.')),
            ],
            options={
                'verbose_name': 'Page Hero Setting',
                'verbose_name_plural': 'Page Hero Settings',
            },
        ),
    ]
