# Generated by Django 6.0.3 on 2026-04-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_pagehero'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='Paste SVG code here. If provided, it will be used instead of the image/URL.'),
        ),
    ]
