# Generated by Django 6.0.3 on 2026-04-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_service_icon_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='Paste SVG code here.'),
        ),
        migrations.AddField(
            model_name='missionvision',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='Paste SVG code here.'),
        ),
    ]
