# Generated by Django 6.0.3 on 2026-04-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_counter_icon_svg_missionvision_icon_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='Paste SVG logo code here. Used if provided.'),
        ),
    ]
