# Generated by Django 6.0.3 on 2026-04-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_partner_icon_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Removed')], default=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Removed')], default=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Removed')], default=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Removed')], default=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='whyuscard',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Removed')], default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Removed')], default=True, verbose_name='Status'),
        ),
    ]
