# Generated by Django 6.0.3 on 2026-04-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_counter_is_active_galleryitem_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionvision',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Hidden')], default=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Hidden')], default=True, verbose_name='Status'),
        ),
    ]
