# Generated by Django 6.0.3 on 2026-04-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_missionvision_is_active_pagehero_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='experience_label',
            field=models.CharField(default='Years of Trust', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='experience_value',
            field=models.CharField(default='12+', help_text='e.g. 12+, 500+', max_length=20),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(blank=True, help_text='Primary image for the story section.', null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='image_alt',
            field=models.CharField(blank=True, default='JKR Story Image', max_length=255),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='image_url',
            field=models.URLField(blank=True, help_text='External URL for primary image.', null=True),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='alignment',
            field=models.CharField(choices=[('center', 'Center'), ('left', 'Left'), ('right', 'Right')], default='center', max_length=20),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='button_2_link',
            field=models.CharField(blank=True, help_text='Link for secondary button.', max_length=255),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='button_2_text',
            field=models.CharField(blank=True, help_text='Secondary button text.', max_length=100),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='button_link',
            field=models.CharField(blank=True, help_text='Link for primary button.', max_length=255),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='button_text',
            field=models.CharField(blank=True, help_text='Primary button text.', max_length=100),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='title_html',
            field=models.CharField(blank=True, help_text="HTML Title (e.g. Our <span class='italic text-primary'>Legacy</span>). If provided, overrides Title.", max_length=512),
        ),
    ]
