# Generated by Django 6.0.3 on 2026-04-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_aboutus_experience_label_aboutus_experience_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='image_alt',
            field=models.CharField(blank=True, help_text='SEO Alt Text', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='missionvision',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='logo_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
