# Generated by Django 6.0.3 on 2026-04-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_galleryitem_image_alt_missionvision_image_alt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(default='Get in Touch', max_length=100)),
                ('heading_html', models.CharField(default="Let's Start a <span class='italic text-primary'>Conversation</span>", max_length=512)),
                ('subtitle', models.TextField(default='We are here to provide excellence and support for your every inquiry.')),
                ('hours_label', models.CharField(default='Monday - Friday', max_length=100)),
                ('hours_value', models.CharField(default='08:30 AM — 05:00 PM', max_length=100)),
                ('form_title_html', models.CharField(default="Have a <span class='italic text-primary'>Question?</span>", max_length=512)),
                ('form_subtitle', models.TextField(default='Send us a message and our specialists will reach out to you within 24 business hours.')),
                ('support_image', models.ImageField(blank=True, null=True, upload_to='contact/')),
                ('support_image_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Page Settings',
            },
        ),
        migrations.AddField(
            model_name='aboutus',
            name='legacy_subtitle',
            field=models.TextField(default='Defining excellence in the international trade landscape for over a decade.', help_text='Subtitle for the About page hero section.'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='legacy_title',
            field=models.CharField(default='Our Legacy', help_text='Title for the About page hero section.', max_length=255),
        ),
    ]
