# Generated by Django 6.0.3 on 2026-04-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_contactpage_aboutus_legacy_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagehero',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO Meta Description.', null=True),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='SEO Keywords.', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO Title Tag. If empty, Page Title will be used.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO Meta Description.', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='SEO Keywords (comma separated).', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO Title Tag. If empty, Service Title will be used.', max_length=255, null=True),
        ),
    ]
