"""
Django settings for jkr project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import environ
import os
import cloudinary
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, True),
    IS_PRODUCTION=(bool, False),
)
# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'), overwrite=True)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-build-placeholder-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['*'])

CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[
    'https://ecom.creativegradientz.com',
    'https://admin.creativegradientz.com',
    'https://creativegradientz.com',
    'https://admin-production-dac3.up.railway.app',
    'https://*.up.railway.app'
])

# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Must be before django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',
    'django.contrib.staticfiles',
    'cloudinary',

    # Third-party apps
    'ckeditor',
    'ckeditor_uploader',
    'import_export',
    'rest_framework', # Added for Category API

    # Custom apps
    'accounts',
    'core',
    'products',
    'orders',
    'sliders',
    'pages',
    'contact',
    'blog',
    'ai_manager',
]

# Authentication Settings
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'core:home'
LOGOUT_REDIRECT_URL = 'core:home'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # For static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.common.BrokenLinkEmailsMiddleware',
    'django.middleware.http.ConditionalGetMiddleware',
]

# ── Security Hardening ────────────────────────────────────────────────────────
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'SAMEORIGIN'

IS_PRODUCTION = env.bool('IS_PRODUCTION', default=False)
if IS_PRODUCTION:
    # Essential for Railway/Heroku to detect HTTPS via proxy
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
    SECURE_REFERRER_POLICY = 'same-origin'

ROOT_URLCONF = 'jkr.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.site_settings', 
                'core.context_processors.page_heroes', 
                'orders.context_processors.cart_count', 
            ],
        },
    },
]

WSGI_APPLICATION = 'jkr.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if env('DATABASE_URL', default=None):
    DATABASES = {
        'default': env.db()
    }
    # Ensure SSL is required for production DBs (Neon/Supabase)
    if IS_PRODUCTION and DATABASES['default'].get('ENGINE') == 'django.db.backends.postgresql':
        DATABASES['default'].setdefault('OPTIONS', {})
        DATABASES['default']['OPTIONS']['sslmode'] = 'require'
    
    DATABASES['default']['CONN_MAX_AGE'] = 600
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator' },
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator' },
    { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator' },
    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator' },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Dubai'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise storage to handle static files in production
# Storage handling moved to STORAGES below
WHITENOISE_USE_FINDERS = True
WHITENOISE_MANIFEST_STRICT = False
WHITENOISE_COMPRESS = False
WHITENOISE_KEEP_ONLY_HASHED_FILES = False

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Modern Django 5.2/6.0 Storage Configuration
# Storage Configuration (Classic mode for maximum compatibility with Cloudinary/WhiteNoise)
if IS_PRODUCTION:
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
    STATICFILES_STORAGE = 'whitenoise.storage.StaticFilesStorage'
else:
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# Modern Django dictionary (fallback)
STORAGES = {
    "default": {"BACKEND": DEFAULT_FILE_STORAGE},
    "staticfiles": {"BACKEND": STATICFILES_STORAGE},
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CKEditor Configuration
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"

# Jazzmin Admin Theme Configuration
JAZZMIN_SETTINGS = {
    "site_title": "Demo Administration",
    "site_header": "Demo Admin",
    "site_brand": "Demo International",
    "site_logo": "assets/logo.png",
    "welcome_sign": "Welcome to Demo Management System",
    "search_model": ["products.Product", "blog.Post"],
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "AI Store Manager", "url": "/ai-manager/dashboard/", "new_window": False},
        {"name": "View Site", "url": "/", "new_window": True},
    ],
    "order_with_respect_to": [
        "products", "orders", "core", "pages", "contact", "blog", "sliders", "auth"
    ],
    "icons": {
        "auth": "fas fa-users-cog", "auth.user": "fas fa-user", "auth.Group": "fas fa-users",
        "products.Product": "fas fa-box-open", "products.Category": "fas fa-tags",
        "products.ProductSKU": "fas fa-barcode", "orders.CustomerOrder": "fas fa-shopping-basket",
        "core.SiteSettings": "fas fa-cogs", "pages.Page": "fas fa-file-alt",
        "contact.QuoteEnquiry": "fas fa-envelope-open-text", "blog.Post": "fas fa-newspaper",
        "sliders.Slider": "fas fa-images",
    },
    "custom_css": "admin/css/admin_premium.css",
    "custom_js": "admin/js/ai_agent.js",
}

STRIPE_SECRET_KEY = env('STRIPE_SECRET_KEY', default='sk_test_12345')
STRIPE_PUBLISHABLE_KEY = env('STRIPE_PUBLISHABLE_KEY', default='pk_test_12345')
STRIPE_WEBHOOK_SECRET = env('STRIPE_WEBHOOK_SECRET', default=None)

# Cloudinary Storage Dictionary (Required by django-cloudinary-storage)
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': env('CLOUDINARY_CLOUD_NAME', default='dltest'),
    'API_KEY': env('CLOUDINARY_API_KEY', default='1234567'),
    'API_SECRET': env('CLOUDINARY_API_SECRET', default='secretkey'),
}

cloudinary.config(
  cloud_name = CLOUDINARY_STORAGE['CLOUD_NAME'],
  api_key = CLOUDINARY_STORAGE['API_KEY'],
  api_secret = CLOUDINARY_STORAGE['API_SECRET']
)

SITE_URL = env('SITE_URL', default='http://localhost:8000')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default=env('EMAIL_HOST_USER', default='notifications@jkrinternational.com'))
CURRENCY = env('CURRENCY', default='AED')

EMAIL_BACKEND = env('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com') 
EMAIL_PORT = env('EMAIL_PORT', cast=int, default=587)
EMAIL_USE_TLS = env('EMAIL_USE_TLS', cast=bool, default=True)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}
