# Generated by Django 6.0.3 on 2026-04-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='post',
                    name='excerpt',
                    field=models.TextField(blank=True, help_text='Short description for the blog card on the listing page.'),
                ),
                migrations.AddField(
                    model_name='post',
                    name='meta_description',
                    field=models.TextField(blank=True),
                ),
                migrations.AddField(
                    model_name='post',
                    name='meta_title',
                    field=models.CharField(blank=True, max_length=255),
                ),
            ],
            database_operations=[]  # Tables and columns already exist in DB
        ),
    ]
