# Generated by Django 6.0.3 on 2026-04-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_excerpt_and_seo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image_url',
            field=models.URLField(blank=True, help_text='Alternative: Direct link to an externally hosted image.', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Blog Cover. Recommended: 1200x800px. JPG, WEBP. Max 2MB.', null=True, upload_to='blog/'),
        ),
    ]
