# Generated by Django 6.0.3 on 2026-04-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_featured_image_url_alter_post_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='SEO Keywords.'),
        ),
    ]
