# Generated by Django 6.0.3 on 2026-04-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_customerorder_is_guest_customerorder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderitem',
            name='regular_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Regular price before offer', max_digits=10),
        ),
    ]
