# Generated by Django 6.0.3 on 2026-04-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_orderitem_sku_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='billing_address_same_as_shipping',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='billing_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='billing_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='billing_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='billing_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='billing_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='billing_street',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='trn',
            field=models.CharField(blank=True, help_text='UAE TRN (exactly 15 digits)', max_length=15, null=True, verbose_name='TRN Number'),
        ),
    ]
