# Generated by Django 6.0.3 on 2026-04-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_customerorder_billing_address_same_as_shipping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total tax amount for this order', max_digits=10),
        ),
        migrations.AddField(
            model_name='customerorderitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax amount for this item', max_digits=10),
        ),
        migrations.AddField(
            model_name='customerorderitem',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='VAT percentage at time of order', max_digits=5),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Grand Total (Items + Shipping + Tax)', max_digits=12),
        ),
    ]
