# Generated by Django 6.0.3 on 2026-04-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_customerorder_tax_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='billing_emirates',
            field=models.CharField(blank=True, choices=[('Abu Dhabi', 'Abu Dhabi'), ('Dubai', 'Dubai'), ('Sharjah', 'Sharjah'), ('Ajman', 'Ajman'), ('Umm Al Quwain', 'Umm Al Quwain'), ('Ras Al Khaimah', 'Ras Al Khaimah'), ('Fujairah', 'Fujairah')], max_length=50),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='billing_street2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Billing Street Address 2'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='emirates',
            field=models.CharField(choices=[('Abu Dhabi', 'Abu Dhabi'), ('Dubai', 'Dubai'), ('Sharjah', 'Sharjah'), ('Ajman', 'Ajman'), ('Umm Al Quwain', 'Umm Al Quwain'), ('Ras Al Khaimah', 'Ras Al Khaimah'), ('Fujairah', 'Fujairah')], default='Dubai', max_length=50),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='street2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Street Address 2'),
        ),
        migrations.AddField(
            model_name='quoteenquiry',
            name='emirates',
            field=models.CharField(blank=True, max_length=100, verbose_name='Emirate/State'),
        ),
        migrations.AddField(
            model_name='quoteenquiry',
            name='street2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Street Address 2'),
        ),
    ]
