# Generated by Django 6.0.3 on 2026-04-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_customerorder_billing_emirates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total promotional discount', max_digits=10),
        ),
        migrations.AddField(
            model_name='customerorderitem',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Site price at time of order', max_digits=10),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Grand Total (Items - Discount + Shipping + Tax)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='customerorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final price after item discounts', max_digits=10),
        ),
    ]
