# Generated by Django 6.0.3 on 2026-03-30 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsku',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productsku',
            name='shipping_charge',
        ),
    ]
