# Generated by Django 6.0.3 on 2026-03-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_attribute_alter_productsku_delivery_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, help_text='Alternative: Direct link to an externally hosted image.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Alternative: Direct link to an externally hosted image.', null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='Alternative: Direct link to an externally hosted image.', null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/gallery/'),
        ),
    ]
