# Generated by Django 6.0.3 on 2026-03-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productimage_options_category_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsku',
            name='additional_shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Extra shipping fee in AED', max_digits=10),
        ),
        migrations.AddField(
            model_name='productsku',
            name='free_shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='height',
            field=models.FloatField(default=0.0, help_text='in cm'),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='length',
            field=models.FloatField(default=0.0, help_text='in cm'),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='shipping_status',
            field=models.CharField(choices=[('available', 'In Stock'), ('out_of_stock', 'Out of Stock'), ('pre_order', 'Pre-Order')], default='available', max_length=50),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='sku_id',
            field=models.CharField(blank=True, help_text='Auto-generated if left blank.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='title',
            field=models.CharField(blank=True, help_text='e.g. Small, Blue, standard, etc.', max_length=255),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('box', 'Box'), ('set', 'Set')], default='pcs', max_length=20),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='weight',
            field=models.FloatField(default=0.0, help_text='in kg'),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='width',
            field=models.FloatField(default=0.0, help_text='in cm'),
        ),
    ]
