# Generated by Django 6.0.3 on 2026-03-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productsku_additional_shipping_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended: 512x512px. JPG, PNG, WEBP. Max 1MB.', null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brochure',
            field=models.FileField(blank=True, help_text='PDF format recommended.', null=True, upload_to='brochures/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Primary Product Image. Recommended: 1000x1000px. JPG, PNG, WEBP. Max 2MB.', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Gallery Image. Recommended: 1000x1000px. JPG, PNG, WEBP. Max 2MB.', null=True, upload_to='products/gallery/'),
        ),
    ]
