# Generated by Django 6.0.3 on 2026-03-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_meta_description_product_meta_description_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='regular_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='additional_shipping_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Extra shipping fee in AED', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='height',
            field=models.FloatField(blank=True, help_text='in cm', null=True),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='length',
            field=models.FloatField(blank=True, help_text='in cm', null=True),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='weight',
            field=models.FloatField(blank=True, help_text='in kg', null=True),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='width',
            field=models.FloatField(blank=True, help_text='in cm', null=True),
        ),
    ]
