# Generated by Django 6.0.3 on 2026-03-30 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_regular_price_alter_product_sale_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='canonical_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='google_seo_keywords',
        ),
    ]
