# Generated by Django 6.0.3 on 2026-03-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_product_canonical_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_description_ar',
            field=models.TextField(blank=True, verbose_name='Meta Description (AR)'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_en',
            field=models.TextField(blank=True, verbose_name='Meta Description (EN)'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO Meta Keywords'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta Keywords (AR)'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta Keywords (EN)'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title Tag (AR)'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title Tag (EN)'),
        ),
        migrations.AddField(
            model_name='category',
            name='url_alias',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO URL Alias'),
        ),
        migrations.AddField(
            model_name='category',
            name='url_alias_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='URL Alias (AR)'),
        ),
        migrations.AddField(
            model_name='category',
            name='url_alias_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='URL Alias (EN)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='SEO Meta Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO Title Tag'),
        ),
    ]
