# Generated by Django 6.0.3 on 2026-04-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_productattributevalue_attribute_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='banner_url',
            field=models.URLField(blank=True, help_text='Alternative: Direct link to an externally hosted banner image.', null=True),
        ),
    ]
