# Generated by Django 6.0.3 on 2026-04-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_collection_banner_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='Paste SVG icon code here. Used if provided.'),
        ),
    ]
