# Generated by Django 6.0.3 on 2026-04-06 21:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_category_icon_svg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='meta_description_ar',
        ),
        migrations.RemoveField(
            model_name='category',
            name='meta_description_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='meta_keywords_ar',
        ),
        migrations.RemoveField(
            model_name='category',
            name='meta_keywords_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='meta_title_ar',
        ),
        migrations.RemoveField(
            model_name='category',
            name='meta_title_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='url_alias',
        ),
        migrations.RemoveField(
            model_name='category',
            name='url_alias_ar',
        ),
        migrations.RemoveField(
            model_name='category',
            name='url_alias_en',
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description for SEO and category page header.'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The immediate parent of this category. Leave blank for a top-level category.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='products_ca_parent__f3c24e_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='products_ca_slug_da4386_idx'),
        ),
    ]
