# Generated by Django 6.0.3 on 2026-04-07 22:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_orderitem_sku_orderitem_product'),
        ('products', '0021_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributeoption',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productsku',
            name='product',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='skus',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='skus',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='products_ca_parent__f3c24e_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='products_ca_slug_da4386_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_keywords_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_title_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='url_alias',
        ),
        migrations.RemoveField(
            model_name='product',
            name='url_alias_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='url_alias_en',
        ),
        migrations.AddField(
            model_name='collection',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='collections', to='products.product'),
        ),
        migrations.AddField(
            model_name='offer',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='offers', to='products.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='additional_shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='free_shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='In-Stock Quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_meta_data',
            field=models.JSONField(blank=True, default=dict, help_text='Stores multilingual SEO tags.'),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_status',
            field=models.CharField(choices=[('available', 'In Stock'), ('out_of_stock', 'Out of Stock'), ('pre_order', 'Pre-Order')], default='available', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='sku_id',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='SKU ID'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('box', 'Box'), ('set', 'Set')], default='pcs', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='collections/'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='banner_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('percentage', 'Percentage Discount (%)'), ('fixed', 'Fixed Discount Entry (AED)'), ('final', 'Final Set Price (AED)')], default='percentage', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='brochures/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, help_text='Key features (one per line)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Primary Product Image.', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description_ar',
            field=models.TextField(blank=True, verbose_name='SEO Meta Description (Arabic)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_keywords_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO Meta Keywords (Arabic)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO Title Tag (Arabic)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='technical_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Product Characteristics & Specifications'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/gallery/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AttributeOption',
        ),
        migrations.DeleteModel(
            name='ProductAttributeValue',
        ),
        migrations.DeleteModel(
            name='ProductSKU',
        ),
        migrations.RemoveField(
            model_name='category',
            name='attributes',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
