# Generated by Django 6.0.3 on 2026-04-08 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_remove_category_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta Description (EN)'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_ar',
            field=models.TextField(blank=True, verbose_name='Meta Description (AR)'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords',
            field=models.TextField(blank=True, verbose_name='Meta Keywords (EN)'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords_ar',
            field=models.TextField(blank=True, verbose_name='Meta Keywords (AR)'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta Title (EN)'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta Title (AR)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta Description (EN)'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_ar',
            field=models.TextField(blank=True, verbose_name='Meta Description (AR)'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords',
            field=models.TextField(blank=True, verbose_name='Meta Keywords (EN)'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords_ar',
            field=models.TextField(blank=True, verbose_name='Meta Keywords (AR)'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta Title (EN)'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta Title (AR)'),
        ),
    ]
