# Generated by Django 6.0.3 on 2026-04-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_category_is_active_category_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Remove')], default=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_on_homepage',
            field=models.BooleanField(choices=[(True, 'Enabled'), (False, 'Disabled')], default=False, verbose_name='Homepage Display'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Remove')], default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='category',
            name='show_on_homepage',
            field=models.BooleanField(choices=[(True, 'Enabled'), (False, 'Disabled')], default=False, verbose_name='Homepage Display'),
        ),
        migrations.AlterField(
            model_name='product',
            name='free_shipping',
            field=models.BooleanField(choices=[(True, 'Enabled'), (False, 'Disabled')], default=False, verbose_name='Free Shipping'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Remove')], default=True, verbose_name='Status'),
        ),
    ]
