
# Generated by Django 6.0.3 on 2026-04-10 08:32

from django.db import migrations

def sync_category_hierarchy(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    Product = apps.get_model('products', 'Product')
    
    # Map of child keywords to parent category names
    AUTO_LINK_MAP = {
        'Wheelchair': 'Wheelchairs',
        'Compression': 'Compression Stockings',
        'Surgical': 'Surgical Supplies',
        'Medical': 'Medical Equipment',
        'Furniture': 'Hospital Furniture',
        'Diagnostic': 'Diagnostic Tools',
        'Laboratory': 'Laboratory',
        'Consumable': 'Consumables',
    }

    # 1. Merge Duplicates (Root categories with same/similar names)
    MERGE_MAP = {
        'Homecare': 'Home Care',
        'Hospital Equipment & Furniture': 'Hospital Furniture',
    }
    
    for old_name, target_name in MERGE_MAP.items():
        old_cat = Category.objects.filter(name__iexact=old_name).first()
        target_cat = Category.objects.filter(name__iexact=target_name).first()
        
        if old_cat and target_cat and old_cat.id != target_cat.id:
            # Move products
            Product.objects.filter(category=old_cat).update(category=target_cat)
            # Move children
            Category.objects.filter(parent=old_cat).update(parent=target_cat)
            # Delete old
            old_cat.delete()
            
    # 2. Duplicate Wheelchairs Merge
    wheelchairs = list(Category.objects.filter(name__iexact='Wheelchairs', parent__isnull=True))
    if len(wheelchairs) > 1:
        target = wheelchairs[0]
        for other in wheelchairs[1:]:
            Product.objects.filter(category=other).update(category=target)
            Category.objects.filter(parent=other).update(parent=target)
            other.delete()

    # 3. Auto-Keyword Linking for orphans
    all_cats = list(Category.objects.all())
    for cat in all_cats:
        if cat.parent:
            continue
            
        is_master = any(cat.name.strip().lower() == v.lower() for v in AUTO_LINK_MAP.values())
        if is_master:
            continue
            
        for keyword, parent_name in AUTO_LINK_MAP.items():
            if keyword.lower() in cat.name.lower():
                parent = next((p for p in all_cats if p.name.strip().lower() == parent_name.lower()), None)
                if parent and cat.id != parent.id:
                    cat.parent = parent
                    cat.save()
                    break

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_category_options_alter_product_category'),
    ]

    operations = [
        migrations.RunPython(sync_category_hierarchy),
    ]
