# Generated by Django 6.0.3 on 2026-04-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_sync_category_hierarchy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='meta_description_ar',
        ),
        migrations.RemoveField(
            model_name='category',
            name='meta_keywords_ar',
        ),
        migrations.RemoveField(
            model_name='category',
            name='meta_title_ar',
        ),
        migrations.RemoveField(
            model_name='category',
            name='seo_meta_data',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_description_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_keywords_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_title_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_meta_data',
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_keywords',
            field=models.TextField(blank=True, verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta Title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_keywords',
            field=models.TextField(blank=True, verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta Title'),
        ),
    ]
