# Generated by Django 6.0.3 on 2026-04-10 17:47

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_remove_category_meta_description_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brochure',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='brochures/'),
        ),
    ]
