# Generated by Django 6.0.3 on 2026-04-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_product_brochure'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='VAT (%)'),
        ),
    ]
