# Generated by Django 6.0.3 on 2026-04-11 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_remove_product_brochure_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('logo', models.ImageField(blank=True, help_text='Brand Logo. Recommended: 300x120px. PNG, WEBP.', null=True, upload_to='brands/')),
                ('logo_url', models.URLField(blank=True, help_text='Alternative: Direct link to an externally hosted logo.', null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(choices=[(True, 'Active'), (False, 'Remove')], default=True, verbose_name='Status')),
                ('show_on_homepage', models.BooleanField(default=False, verbose_name='Homepage Display')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Apply to all products in these categories (and subcategories).', related_name='bulk_offers', to='products.category'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Individual product assignment.', related_name='offers', to='products.product'),
        ),
        migrations.AddField(
            model_name='offer',
            name='brands',
            field=models.ManyToManyField(blank=True, help_text='Apply to all products of these brands.', related_name='bulk_offers', to='products.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand'),
        ),
    ]
