# Generated by Django 6.0.3 on 2026-04-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_brand_offer_categories_alter_offer_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Removed')], default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='show_on_homepage',
            field=models.BooleanField(choices=[(True, 'Enabled'), (False, 'Disabled')], default=False, verbose_name='Homepage Display'),
        ),
    ]
