# Generated by Django 6.0.3 on 2026-04-14 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_brand_order_alter_brand_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='is_active',
        ),
    ]
