# Generated by Django 6.0.3 on 2026-04-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_remove_brand_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alternative Text'),
        ),
    ]
