# Generated by Django 6.0.3 on 2026-04-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_productimage_image_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_alt',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Alternative Text'),
        ),
    ]
