# Generated by Django 6.0.3 on 2026-04-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_alter_productimage_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=3, verbose_name='Average Rating'),
        ),
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Review Count'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alternative Text'),
        ),
    ]
