# Generated by Django 6.0.3 on 2026-04-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_product_avg_rating_product_review_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, help_text='Small badge text (e.g. NEW, TRENDING)', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='badge_color',
            field=models.CharField(choices=[('blue', 'Blue'), ('red', 'Red'), ('green', 'Green'), ('dark', 'Dark'), ('gold', 'Gold')], default='blue', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured Product'),
        ),
    ]
