# Generated by Django 6.0.3 on 2026-04-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_product_badge_product_badge_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Remove')], default=True, verbose_name='Status'),
        ),
    ]
