# Generated by Django 6.0.3 on 2026-04-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_brand_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_alt',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Alternative Text'),
        ),
    ]
