# Generated by Django 6.0.3 on 2026-04-15 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_alter_productimage_image_alt'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE products_productimage ALTER COLUMN image_alt DROP NOT NULL;',
            reverse_sql='ALTER TABLE products_productimage ALTER COLUMN image_alt SET NOT NULL;',
        ),
    ]
