# Generated by Django 6.0.3 on 2026-04-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_auto_20260415_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alternative Text'),
        ),
    ]
