# Generated by Django 6.0.3 on 2026-04-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_alter_productimage_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Descriptive text for the category image.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='banner_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
