# Generated by Django 6.0.3 on 2026-04-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_category_image_alt_collection_banner_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='layout',
            field=models.CharField(choices=[('1_col', '1-Image (Full Width)'), ('2_col', '2-Images (50% Width)'), ('3_col', '3-Images (33% Width)')], default='3_col', help_text='Determine the visual size of this collection on the homepage grid.', max_length=20),
        ),
    ]
