# Generated by Django 6.0.3 on 2026-04-18 10:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_collection_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='include_fast_delivery_badge',
            field=models.BooleanField(default=True, verbose_name="Show 'Fast Delivery' Badge"),
        ),
        migrations.AddField(
            model_name='product',
            name='include_genuine_badge',
            field=models.BooleanField(default=True, verbose_name="Show 'Genuine Product' Badge"),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_returns',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Shipping & Returns Policy'),
        ),
    ]
