# Generated by Django 6.0.3 on 2026-04-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_product_include_fast_delivery_badge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_svg', models.TextField(blank=True, help_text='Paste SVG icon code here (e.g., from Lucide or Heroicons).')),
                ('background_color', models.CharField(default='#ecfdf5', help_text='e.g., #ecfdf5 (Light green)', max_length=50)),
                ('text_color', models.CharField(default='#065f46', help_text='e.g., #065f46 (Dark green)', max_length=50)),
                ('border_color', models.CharField(default='#d1fae5', help_text='e.g., #d1fae5', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Trust Badge',
                'verbose_name_plural': 'Trust Badges',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='include_fast_delivery_badge',
        ),
        migrations.RemoveField(
            model_name='product',
            name='include_genuine_badge',
        ),
        migrations.AddField(
            model_name='product',
            name='trust_badges',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.trustbadge'),
        ),
    ]
