# Generated by Django 6.0.3 on 2026-04-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_trustbadge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trustbadge',
            name='icon_svg',
            field=models.TextField(blank=True, help_text="Paste SVG icon code here. You can use <a href='https://lucide.dev/icons' target='_blank' style='color:#007bff; font-weight:bold;'>Lucide Icons</a> to find and copy icons."),
        ),
    ]
