# Generated by Django 6.0.3 on 2026-04-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_alter_trustbadge_icon_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='brand',
            name='meta_keywords',
            field=models.TextField(blank=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='brand',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta Title'),
        ),
    ]
