# Generated by Django 6.0.3 on 2026-04-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_brand_meta_description_brand_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product_count',
            field=models.PositiveIntegerField(default=0, help_text='Denormalized count for performance.', verbose_name='Cached Product Count'),
        ),
    ]
