# Generated by Django 6.0.3 on 2026-04-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_category_product_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='homepage_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Homepage Display Order'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Remove')], db_index=True, default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='category',
            name='show_on_homepage',
            field=models.BooleanField(choices=[(True, 'Enabled'), (False, 'Disabled')], db_index=True, default=False, verbose_name='Homepage Display'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Featured Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(db_index=True, default=0, verbose_name='In-Stock Quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_status',
            field=models.CharField(choices=[('available', 'In Stock'), ('out_of_stock', 'Out of Stock'), ('pre_order', 'Pre-Order')], db_index=True, default='available', max_length=50),
        ),
    ]
