# Generated by Django 6.0.3 on 2026-04-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0051_alter_brand_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description for SEO and category page header.', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='Paste SVG icon code here. Used if provided.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, help_text='Small badge text (e.g. NEW, TRENDING)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, help_text='Key features (one per line)', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='SKU ID'),
        ),
    ]
